development:
  cloud_name: dfifcytph
  api_key: '587412989829586'
  api_secret: MXmveWCbMv7NtDYtD3dlsUlK6WE
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dfifcytph
  api_key: '587412989829586'
  api_secret: MXmveWCbMv7NtDYtD3dlsUlK6WE
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dfifcytph
  api_key: '587412989829586'
  api_secret: MXmveWCbMv7NtDYtD3dlsUlK6WE
  enhance_image_tag: true
  static_file_support: false